# Generated by Django 5.2.4 on 2025-08-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creator_address', models.CharField(max_length=42)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('floor_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('total_volume', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('total_items', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['-total_volume'],
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('token_uri', models.URLField()),
                ('owner_address', models.CharField(max_length=42)),
                ('creator_address', models.CharField(max_length=42)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('is_listed', models.BooleanField(default=False)),
                ('is_auction', models.BooleanField(default=False)),
                ('auction_end_time', models.DateTimeField(blank=True, null=True)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('highest_bidder', models.CharField(blank=True, max_length=42, null=True)),
                ('royalty_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('collection', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nfts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=42, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('discord', models.CharField(blank=True, max_length=255, null=True)),
                ('total_created', models.IntegerField(default=0)),
                ('total_collected', models.IntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('transaction_type', models.CharField(choices=[('mint', 'Mint'), ('list', 'List'), ('buy', 'Buy'), ('bid', 'Bid'), ('transfer', 'Transfer'), ('delist', 'Delist')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('block_number', models.IntegerField()),
                ('gas_used', models.IntegerField()),
                ('gas_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft.nft')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(default='0x0000000000000000000000000000000000000000', max_length=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft.nft')),
            ],
            options={
                'db_table': 'favorites',
                'unique_together': {('user_address', 'nft')},
            },
        ),
    ]
