# Generated by Django 5.2.4 on 2025-08-07 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0004_auto_20250806_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenSeaFavorite',
        ),
    ]
