# Generated by Django 5.2.4 on 2025-08-07 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0005_remove_opensea_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nft.nft'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('mint', 'Mint'), ('list', 'List'), ('buy', 'Buy'), ('bid', 'Bid'), ('transfer', 'Transfer'), ('delist', 'Delist'), ('follow', 'Follow'), ('unfollow', 'Unfollow')], max_length=20),
        ),
    ]
