# Generated by Django 5.2.4 on 2025-08-07 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0006_alter_transaction_nft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_address', models.CharField(blank=True, max_length=42, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='nft.nft')),
            ],
            options={
                'db_table': 'nft_views',
                'ordering': ['-viewed_at'],
                'unique_together': {('nft', 'viewer_address', 'ip_address')},
            },
        ),
    ]
